### PR TITLE
Cancel check-in

### LINKED ISSUE #521: Not allowing to cancel checkin
Actual Results
--
The system is not providing the controls to cancel a checkin 

Expected results
--
The system should allow to cancel checkin but only if there is no clinical service saved or edited in the visit.

Steps to reproduce
--
Login > Registration or Pharmacy module > Checkin section

Screenshot/Attachment (Optional)
--
A visual description of the unexpected behaviour.
image

### PR DESCRIPTION
**Pull request by ynurmahomed**
Fixes #521.

### CODE REVIEW

**Comment by ynurmahomed** [comment]
[Allow check-in cancellation](https://trello.com/c/CJrxpd1g/4-allow-check-in-cancellation)

File: app/visit/components/checkIn.js [hunk 1]
```diff
@@ -22,6 +22,7 @@
 
     vm.$onChanges = $onChanges;
     vm.checkIn = checkIn;
+    vm.cancelCheckIn = cancelCheckIn;
 
     function $onChanges(changesObj) {
       var patient = changesObj.patient.currentValue;
```
Comment (drryanjames) [inline app/visit/components/checkIn.js]: Is vm.disableCheckin still used? Line 34 sets it but it looks like all other references were deleted in this check in.

File: app/visit/components/checkIn.js [hunk 2]
```diff
@@ -6,7 +6,7 @@
     .component('checkIn', {
       bindings: {
         patient: '<',
-        onCheckIn: '&'
+        onCheckInChange: '&'
```
Comment (drryanjames) [inline app/visit/components/checkIn.js]: Just curious: does this bind ```vm.onCheckInChange``` to the ```on-check-in-change``` attribute, so when you call ```vm.onCheckInChange``` below it runs the attribute's value (in this case ```vm.reload()```)?

File: app/visit/visitService.js [hunk 3]
```diff
@@ -60,6 +61,17 @@
       }
     }
 
+    function deleteVisit(visit) {
+      return $http.delete(Bahmni.Common.Constants.visitUrl + '/' + visit.uuid, {params: {purge: true}})
```
Comment (drryanjames) [inline app/visit/visitService.js]: Why purge?

File: test/unitTests/spec/visit/components/checkIn.spec.js [hunk 4]
```diff
@@ -98,34 +98,75 @@ describe('CheckInController', function () {
...
 
-      var ctrl = $componentController('checkIn', null, { onCheckIn: jasmine.createSpy('onCheckIn') });
+      var ctrl = $componentController('checkIn', null, {onCheckInChange: jasmine.createSpy('onCheckInChange')});
 
-      ctrl.checkIn();
+      ctrl.cancelCheckIn();
       $rootScope.$apply();
 
-      expect(ctrl.onCheckIn).toHaveBeenCalled();
+      expect(ctrl.onCheckInChange).toHaveBeenCalled();
```
Comment (drryanjames) [inline test/unitTests/spec/visit/components/checkIn.spec.js]: How about ```expect(ctrl.onCheckInChange).toHaveBeenCalledTimes(2)``` to make sure it's been called exactly twice?

File: test/unitTests/spec/visit/visitService.spec.js [hunk 5]
```diff
@@ -345,4 +345,22 @@ describe('visitService', function () {
 
   });
 
+  describe('deleteVisit', function () {
+
+    beforeEach(function () {
+      $http.expectDELETE("/openmrs/ws/rest/v1/pocvisit/1234?purge=true").respond(null);
```
Comment (drryanjames) [inline test/unitTests/spec/visit/visitService.spec.js]: I like this expect verify pattern

File: app/visit/components/checkIn.js (hunk 1 above)
Comment (ynurmahomed) [reply app/visit/components/checkIn.js]: Good catch, it's not used anymore. I had removed it [here](https://github.com/esaude/esaude-emr-poc/pull/540/commits/e99eb8d50899b7d4a4dfbe52dcfd402dc6ab54e6) but I guess it came back when I merged `master` into this branch.

File: app/visit/components/checkIn.js (hunk 2 above)
Comment (ynurmahomed) [reply app/visit/components/checkIn.js]: Correct. It's a way of having communication between components, you can pass values from child components to its parents using this kind of binding.

https://docs.angularjs.org/guide/directive#creating-a-directive-that-wraps-other-elements

File: app/visit/visitService.js (hunk 3 above)
Comment (ynurmahomed) [reply app/visit/visitService.js]: I guess its because you can only delete a visit when there are no encounters for it. I thought we would not want to keep visits with no encounters. @Benilde I think this is not yet specified.

File: test/unitTests/spec/visit/components/checkIn.spec.js (hunk 4 above)
Comment (ynurmahomed) [reply test/unitTests/spec/visit/components/checkIn.spec.js]: Is it supposed to be called twice?

Comment (drryanjames) [reply test/unitTests/spec/visit/components/checkIn.spec.js]: Np :). My bad. I thought ```checkIn``` was called before ```cancelCheckIn```
