### PR TITLE
EPCT-13 Default drug dispensation quantity

### LINKED ISSUE #596: [Pharmacy] Dispensation should suggest default dispensing quantity
Actual Results
--
When a prescribed item is selected for dispensation the system is not providing a default quantity in the quantity field.

Expected results
--
When a prescribed item is selected for dispensation the system should provide a default quantity in the quantity field.
The default quantity should be the total prescribed quantity. Except for ARVs with quantity > 30, the default should be 30.

Steps to reproduce
--
Login > Pharmacy module > Dispensation > Select items to dispense > observe the dispensation quantity (currently the default is 1)
Screenshot/Attachment (Optional)
--
A visual description of the unexpected behaviour.

### PR DESCRIPTION
**Pull request by Guimino**
When a prescribed item is selected for dispensation the system should provide a default quantity to pickup in the quantity field.
fix #596

### CODE REVIEW

**Comment by Guimino** [comment]
Needs PR https://github.com/esaude/openmrs-module-pharmacyapi/pull/50

File: app/pharmacy/components/dispensation.js [hunk 1]
```diff
@@ -76,13 +76,15 @@
...
       item.showNextPickupDate = true;
-      item.quantity = item.drugToPickUp;
+      item.quantity = getDefaultQuantityToDispense(item);
       updatePickupDate(item);
-
       vm.selectedPrescriptionItems = vm.selectedPrescriptionItems.concat([item]);
     }
 
-
+    function getDefaultQuantityToDispense(item){
```
Comment (ynurmahomed) [inline app/pharmacy/components/dispensation.js]: Shouldn't this business logic be in `dispensationService`?

Comment (Guimino) [reply app/pharmacy/components/dispensation.js]: moved the business logic to dispensationService service. I don't think is good idea to put default quantity as proper of a resource, it is not attribute a but logic result
