### PR TITLE
fix Not updating WHO stages

### LINKED ISSUE #609: The system is alwasy dissplaying WHO =IV
Actual Results
--
Independently on the stage that the patient is, the system displays the calculated  stage as **IV**  

Expected results
--
The system must display the calculated stage according to the symptoms that the patient has in each stage

Steps to reproduce
--
Login to POC-> Select the registration module-> search for a patient-> Check in the patient-> Go to clinical module-> select the consultation tab-> click on add WHO stage.

Screenshot/Attachment (Optional)
--
image

### PR DESCRIPTION
**Pull request by Guimino**
Fix #609

### CODE REVIEW

**Comment by Guimino** [comment]
[Not updating WHO stages](https://trello.com/c/evQTxTBA/82-not-updating-who-stages)

File: app/common/clinical-services/components/formField.js [hunk 1]
```diff
@@ -151,7 +151,7 @@
 
           if (angular.isDefined(model.value)) {
 
-            if (angular.isDefined(model.value[answer.uuid])) {
+            if (angular.isDefined(model.value[answer.uuid]) && model.value[answer.uuid] != 'undefined') {
```
Comment (ynurmahomed) [inline app/common/clinical-services/components/formField.js]: It's working now, but there is this rule [here](https://eslint.org/docs/rules/eqeqeq) that i think we should be enforcing.

Comment (Guimino) [reply app/common/clinical-services/components/formField.js]: Fixed, please review again.
