### PR TITLE
Handle org.openmrs.util.AttributableDate formats

### LINKED ISSUE #459: [Registration] Error saving patient
Actual Results
--
After filling all patient's details and press "Guardar" system shows error message ""

Expected results
--
System should save patient.

Steps to reproduce
--
POC->registration->New Patient -> fill all categories -> Click Guardar

Screenshot/Attachment (Optional)
--
registration_error_saving

### PR DESCRIPTION
**Pull request by ynurmahomed**
Fix #459.

### CODE REVIEW

File: app/registration/mappers/createPatientRequestMapper.js [hunk 1]
```diff
@@ -75,15 +78,18 @@ Bahmni.Registration.CreatePatientRequestMapper = (function () {
...
+  var setAttributeValue = function (attributeType, attr, value) {
+    if (attributeType.format === "org.openmrs.Concept") {
+      attr.hydratedObject = value;
+    }
+    else if (attributeType.format === "org.openmrs.util.AttributableDate") {
+      attr.value = moment(value).format(DATETIME_FORMAT);
+    } else if (value === "" || value === null || angular.isUndefined(undefined)) {
+      attr.voided = true;
+    } else {
+      attr.value = value.toString().slice(0,50); // person_attribute_type.value is varchar(50), maybe we should validade before.
```
Comment (valvijo) [inline app/registration/mappers/createPatientRequestMapper.js]: Input should validate. I'm creating an issue for this so that we can address in the future.
