### PR TITLE
Fix patient registration tests

### LINKED ISSUE #653: Two Register Patient tests are failing
Actual Results
--
Two test fail when you run ```npm run e2e registerPatient_test.js```

Expected results
--
All tests pass when you run ```npm run e2e registerPatient_test.js```

Steps to reproduce
--
Run ```npm run e2e registerPatient_test.js```

### PR DESCRIPTION
**Pull request by sacuribraimo**
- Translator refactoring
- Fix #653

### CODE REVIEW

File: test/e2eTests/i18n.js [hunk 1]
```diff
@@ -15,30 +14,36 @@ var path = require('path');
...
+    // Each subdirectory represents a module and has it's own locale files
     if (fs.statSync(name).isDirectory()) {
       var files = fs.readdirSync(name);
+
       files.forEach((file) => {
 
         try {
-          locale = path.basename(file).split('.').shift();
-          if (locale.includes("pt")) {
+          fileName = path.basename(file).split('.').shift();
```
Comment (drryanjames) [inline test/e2eTests/i18n.js]: `localeInFilename`, or something similar, might be a better variable name. `Filename` makes it sound  like it's the full file name.

File: test/e2eTests/pages/registerPatientPage.js [hunk 2]
```diff
@@ -45,13 +45,18 @@ class RegisterPatientPage extends Page {
...
       street: { css: '#address1' },
-      provenience: { css: 'form select[id=Proveniência]' },
+      provenience: 'select[id="d10628a7-ba75-4495-840b-bf6f1c44fd2d"]',
       reference: { css: '#Ponto de Referência' },
       phone1: { css: '#Numero de Telefone 1' },
       phone2: { css: '#Numero de Telefone 2' },
-      hivTestDate: { css: '#Data do teste HIV' },
-      testType: { css: '#Tipo de teste HIV' },
-      testResult: { css: '#Resultado do Teste HIV' }
+      hivTestDate: 'input[id="46e79fce-ba89-4ec9-8f31-2dfd9318d415"',
```
Comment (drryanjames) [inline test/e2eTests/pages/registerPatientPage.js]: Will these values always be the same?

Comment (drryanjames) [reply test/e2eTests/pages/registerPatientPage.js]: Seems like it would be safer to use css here. Can you add an attribute to the html, maybe something like `<div ... qa-hivTestDate />` or something like that?

File: test/e2eTests/pages/registerPatientPage.js [hunk 3]
```diff
@@ -78,7 +83,8 @@ class RegisterPatientPage extends Page {
   }
 
   selectGender(patient) {
-    this.I.click(patient.person.gender == 'F' ? this.translate('COMMON_MALE') : this.translate('COMMON_MALE'));
+    const gender = patient.person.gender == 'F' ? 'label[for="patientGenderF"' : 'label[for="patientGenderM"';
```
Comment (drryanjames) [inline test/e2eTests/pages/registerPatientPage.js]: how about ``const genderButton = `label[for="patientGender${patient.person.gender}"]` ``?

File: test/e2eTests/translator.js [hunk 4]
```diff
@@ -0,0 +1,30 @@
+const I18n = require('./i18n');
+
+// Create the translator as a singleton to share the instance across the app
+// Usage: declare it and use the translate function
+// const t = require('./../translator')
+// t.translate(key)
+const translator = (function () {
```
Comment (drryanjames) [inline test/e2eTests/translator.js]: Check [this](http://www.adam-bien.com/roller/abien/entry/singleton_pattern_in_es6_and) out. I think it's a cleaner way to create a singleton that uses ES6 syntax. What do you think?

File: test/e2eTests/pages/registerPatientPage.js (hunk 2 above)
Comment (sacuribraimo) [reply test/e2eTests/pages/registerPatientPage.js]: Yes. I have already edited some of the html to replace name uuid.

File: test/e2eTests/pages/registerPatientPage.js (hunk 3 above)
Comment (sacuribraimo) [reply test/e2eTests/pages/registerPatientPage.js]: Great!

File: test/e2eTests/translator.js (hunk 4 above)
Comment (sacuribraimo) [reply test/e2eTests/translator.js]: Will check and include for next refactoring. Thanks!
